# Generated by Django 3.1.6 on 2021-05-12 19:48

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('type_of_financial_institution', models.CharField(choices=[('1', 'Central Banks'), ('2', 'Retail and Commercial Banks'), ('3', 'Internet Banks'), ('4', 'Credit Unions'), ('5', 'Savings and Loan Associations'), ('6', 'Investment Banks and Companies'), ('7', 'Brokerage Firms'), ('8', 'Insurance Companies'), ('9', 'Mortgage Companies')], default='', max_length=30)),
                ('code', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('street_address', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=256)),
                ('postal_code', models.PositiveIntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'FinancialInstitution',
                'verbose_name_plural': 'FinancialInstitutions',
            },
        ),
    ]
