version: "3.7"

services:
  db:
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - "JOGA_DB_USER=jogadba"
      - "JOGA_DB_PASSWORD=8QxpF-ZdJ%RT9T=NQ-7cFUgr"
      - "JOGA_DB_DATABASE=jogadb"
    build: "./db"

  backend:
    build: .
    command: python manage.py makemigrations --noinput && python /code/manage.py migrate --noinput && python/code/manage.py collectstatic --noinput && python /code/manage.py runserver 0.0.0.0:8001
    environment:
      - "DJANGO_SECRET_KEY=secretkey"
      - "DEBUG=False"
      - "DATABASE_ENGINE=django.db.backends.postgresql"
      - "DATABASE_NAME=jogadb"
      - "DATABASE_USERNAME=jogadba"
      - "DATABASE_PASSWORD=8QxpF-ZdJ%RT9T=NQ-7cFUgr"
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DJANGO_LOGLEVEL=info"
    volumes:
      - .:/code
      - ./static:/app/static
    expose:
      - "8001"
    depends_on:
      - db

  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - ./static:/app/static
    ports:
      - "80:80"
    links:
      - backend

volumes:
  postgres_data:
